// Generated by CoffeeScript 1.10.0
(function() {
  var app, express;

  express = require("express");

  app = express();

  app.get("/random/:min/:max", function(req, res) {
    var max, min, result;
    min = parseInt(req.params.min);
    max = parseInt(req.params.max);
    if (isNaN(min) || isNaN(max)) {
      res.status(400);
      res.json({
        error: "Bad request."
      });
    }
    result = Math.round((Math.random() * (max - min)) + min);
    return res.json({
      result: result
    });
  });

  app.listen(3000, function() {
    return console.log("App Started on port 3000.");
  });

}).call(this);

//# sourceMappingURL=app.js.map
